name: Ubuntu-latest

on: [push, pull_request]

jobs:

  test:
  
    strategy:
      matrix:
        go-version: [1.17]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test with coverage
      run: 
          go test -race -coverprofile=coverage.out -covermode=atomic  ./...

    - name: Process golang coverage data
      # run: echo "ANSWER=42" >> $GITHUB_ENV
      run: |
          set -x
          COVERAGE=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          if (( $(echo "$COVERAGE <= 50" | bc -l) )) ; then
            COLOR=red
          elif (( $(echo "$COVERAGE > 80" | bc -l) )); then
            COLOR=green
          else
            COLOR=orange
          fi
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          echo "COLOR=$COLOR" >> $GITHUB_ENV
    - name: Create gist and coverage badge
      uses: schneegans/dynamic-badges-action@v1.4.0
      with:
        auth: ${{ secrets.SECRET_FOR_GIST_CODECOV_BADGE }}
        gistID: e8460b70055bce6da6713a6bacaed7f7
        filename: xzdummy-codecov.json
        label: codecov
        message: ${{ env.COVERAGE }}
        color: ${{ env.COLOR }}
        #valColorRange: ${{ env.COVERAGE }}
        #maxColorRange: 100
        #minColorRange: 0